### ISSUE TITLE
Publish docker image to docker hub

### ISSUE THREAD

**Issue by rciovati** [abinoda/label-when-approved-action#6]
Every time a PR is approved it takes around 1 minute to build the docker image and then it runs the script. I was wondering if it makes sense to publish a prebuilt docker image to docker hub so that it doesn't need to be built it every time.

**Comment by rciovati** [comment]
Hey @abinoda is this something I can help you with? The GitHub Package Registry will be out of beta soon, perhaps it's a good moment to give it a try: https://github.com/features/package-registry

**Comment by abinoda** [comment]
@rciovati Sure!

**Comment by jobsonmodesto** [comment]
> Every time a PR is approved it takes around 1 minute to build the docker image and then it runs the script. I was wondering if it makes sense to publish a prebuilt docker image to docker hub so that it doesn't need to be built it every time.

I fairly know 100% said true 1% 99c let research time

**Comment by jobsonmodesto** [comment]
Ram it 0.01b

**Comment by jobsonmodesto** [comment]
> @rciovati Sure!

Sound Code

**Comment by jobsonmodesto** [comment]
Atari 2600 ref manual

**Comment by jobsonmodesto** [comment]
Harcoded Video Game Copy

**Comment by jobsonmodesto** [comment]
Metal Gear Solid

**Comment by jobsonmodesto** [comment]
Us Military Spy Quirks Espionage Smoke

**Comment by jobsonmodesto** [comment]
+-

**Comment by jobsonmodesto** [comment]
Begood where you are on and know by heart opensource name request id from

**Comment by jobsonmodesto** [comment]
Tester yesterday

**Comment by jobsonmodesto** [comment]
#complete

**Comment by mattwelke** [comment]
I think this may not be necessary anymore. I'm working on the `github-actions-for-ci` lab which uses this action, and it builds it each time, but it appears to run pretty quick. 17s for me today. Perhaps they've optimized GitHub Actions since this issue was opened:

![image](https://user-images.githubusercontent.com/7719209/95691849-6afdb300-0bf0-11eb-8ae6-5c1b45d81076.png)
